import { Business } from '../types';

// Real Qatar locations (Doha area) with dummy businesses
export const QATAR_BUSINESSES: Omit<Business, 'id' | 'created_at'>[] = [
  {
    name: 'Souq Waqif Coffee House',
    category: 'coffee',
    description: 'Traditional Qatari coffee experience in the heart of Souq Waqif',
    logo_url: 'https://via.placeholder.com/100x100.png?text=Coffee',
    latitude: 25.2867,
    longitude: 51.5333,
    address: 'Souq Waqif, Doha',
    rating: 4.8,
    stamps_required: 10,
    reward_description: 'Free Qahwa & Date Set',
    nfc_tag_id: 'SHOP_SWC001',
    qr_code: 'QR_SWC001',
  },
  {
    name: 'The Pearl Espresso Bar',
    category: 'coffee',
    description: 'Modern coffee shop at Porto Arabia',
    logo_url: 'https://via.placeholder.com/100x100.png?text=Espresso',
    latitude: 25.3717,
    longitude: 51.5408,
    address: 'Porto Arabia, The Pearl',
    rating: 4.6,
    stamps_required: 8,
    reward_description: 'Free Specialty Coffee',
    nfc_tag_id: 'SHOP_PEB002',
    qr_code: 'QR_PEB002',
  },
  {
    name: 'Corniche Cafe',
    category: 'coffee',
    description: 'Seaside cafe with stunning Doha skyline views',
    logo_url: 'https://via.placeholder.com/100x100.png?text=Corniche',
    latitude: 25.3004,
    longitude: 51.5269,
    address: 'Doha Corniche',
    rating: 4.7,
    stamps_required: 10,
    reward_description: 'Free Cappuccino + Pastry',
    nfc_tag_id: 'SHOP_CC003',
    qr_code: 'QR_CC003',
  },
  {
    name: 'West Bay Grill',
    category: 'restaurant',
    description: 'Premium steakhouse in the business district',
    logo_url: 'https://via.placeholder.com/100x100.png?text=Grill',
    latitude: 25.3189,
    longitude: 51.5307,
    address: 'West Bay, Doha',
    rating: 4.9,
    stamps_required: 12,
    reward_description: 'Free Dessert or Appetizer',
    nfc_tag_id: 'SHOP_WBG004',
    qr_code: 'QR_WBG004',
  },
  {
    name: 'Katara Beach Restaurant',
    category: 'restaurant',
    description: 'Mediterranean cuisine by the beach',
    logo_url: 'https://via.placeholder.com/100x100.png?text=Beach',
    latitude: 25.3688,
    longitude: 51.5304,
    address: 'Katara Cultural Village',
    rating: 4.8,
    stamps_required: 10,
    reward_description: 'Free Main Course',
    nfc_tag_id: 'SHOP_KBR005',
    qr_code: 'QR_KBR005',
  },
  {
    name: 'Msheireb Dining',
    category: 'restaurant',
    description: 'Contemporary Qatari cuisine',
    logo_url: 'https://via.placeholder.com/100x100.png?text=Dining',
    latitude: 25.2868,
    longitude: 51.5279,
    address: 'Msheireb Downtown',
    rating: 4.7,
    stamps_required: 10,
    reward_description: 'Free Traditional Meal',
    nfc_tag_id: 'SHOP_MD006',
    qr_code: 'QR_MD006',
  },
  {
    name: 'Aspire Fitness Club',
    category: 'gym',
    description: 'State-of-the-art gym and wellness center',
    logo_url: 'https://via.placeholder.com/100x100.png?text=Gym',
    latitude: 25.2639,
    longitude: 51.4428,
    address: 'Aspire Zone',
    rating: 4.9,
    stamps_required: 15,
    reward_description: 'Free Personal Training Session',
    nfc_tag_id: 'SHOP_AFC007',
    qr_code: 'QR_AFC007',
  },
  {
    name: 'West Bay Sports Center',
    category: 'gym',
    description: 'Premium fitness facility with pool',
    logo_url: 'https://via.placeholder.com/100x100.png?text=Sports',
    latitude: 25.3203,
    longitude: 51.5289,
    address: 'West Bay',
    rating: 4.6,
    stamps_required: 12,
    reward_description: 'Free Week Pass',
    nfc_tag_id: 'SHOP_WBSC008',
    qr_code: 'QR_WBSC008',
  },
  {
    name: 'Luxury Spa at The Pearl',
    category: 'spa',
    description: 'Premium wellness and beauty treatments',
    logo_url: 'https://via.placeholder.com/100x100.png?text=Spa',
    latitude: 25.3755,
    longitude: 51.5425,
    address: 'The Pearl-Qatar',
    rating: 5.0,
    stamps_required: 8,
    reward_description: 'Free 30min Massage',
    nfc_tag_id: 'SHOP_LSP009',
    qr_code: 'QR_LSP009',
  },
  {
    name: 'Doha Beauty Lounge',
    category: 'salon',
    description: 'Modern hair and beauty salon',
    logo_url: 'https://via.placeholder.com/100x100.png?text=Salon',
    latitude: 25.2947,
    longitude: 51.5258,
    address: 'Al Sadd, Doha',
    rating: 4.7,
    stamps_required: 10,
    reward_description: 'Free Haircut or Styling',
    nfc_tag_id: 'SHOP_DBL010',
    qr_code: 'QR_DBL010',
  },
  {
    name: 'Villaggio Mall Fashion',
    category: 'retail',
    description: 'Trendy fashion boutique',
    logo_url: 'https://via.placeholder.com/100x100.png?text=Fashion',
    latitude: 25.2579,
    longitude: 51.4407,
    address: 'Villaggio Mall',
    rating: 4.5,
    stamps_required: 15,
    reward_description: '20% Off Next Purchase',
    nfc_tag_id: 'SHOP_VMF011',
    qr_code: 'QR_VMF011',
  },
  {
    name: 'City Center Bookstore',
    category: 'retail',
    description: 'Wide selection of books and magazines',
    logo_url: 'https://via.placeholder.com/100x100.png?text=Books',
    latitude: 25.3266,
    longitude: 51.5151,
    address: 'City Center Doha',
    rating: 4.6,
    stamps_required: 10,
    reward_description: 'Free Book (up to 50 QAR)',
    nfc_tag_id: 'SHOP_CCB012',
    qr_code: 'QR_CCB012',
  },
  {
    name: 'Al Wakrah Coffee Corner',
    category: 'coffee',
    description: 'Cozy neighborhood cafe',
    logo_url: 'https://via.placeholder.com/100x100.png?text=Corner',
    latitude: 25.1679,
    longitude: 51.6004,
    address: 'Al Wakrah',
    rating: 4.4,
    stamps_required: 8,
    reward_description: 'Free Coffee & Cookie',
    nfc_tag_id: 'SHOP_AWC013',
    qr_code: 'QR_AWC013',
  },
  {
    name: 'Education City Cafe',
    category: 'coffee',
    description: 'Student-friendly cafe with study areas',
    logo_url: 'https://via.placeholder.com/100x100.png?text=Study',
    latitude: 25.3173,
    longitude: 51.4382,
    address: 'Education City',
    rating: 4.5,
    stamps_required: 10,
    reward_description: 'Free Large Coffee',
    nfc_tag_id: 'SHOP_ECC014',
    qr_code: 'QR_ECC014',
  },
  {
    name: 'Lusail Marina Bistro',
    category: 'restaurant',
    description: 'Waterfront dining experience',
    logo_url: 'https://via.placeholder.com/100x100.png?text=Marina',
    latitude: 25.4093,
    longitude: 51.4986,
    address: 'Lusail',
    rating: 4.8,
    stamps_required: 12,
    reward_description: 'Free Seafood Platter',
    nfc_tag_id: 'SHOP_LMB015',
    qr_code: 'QR_LMB015',
  },
  {
    name: 'Al Khor Gym & Fitness',
    category: 'gym',
    description: 'Community fitness center',
    logo_url: 'https://via.placeholder.com/100x100.png?text=Fitness',
    latitude: 25.6807,
    longitude: 51.4969,
    address: 'Al Khor',
    rating: 4.3,
    stamps_required: 10,
    reward_description: 'Free Month Membership',
    nfc_tag_id: 'SHOP_AKG016',
    qr_code: 'QR_AKG016',
  },
  {
    name: 'Barwa Village Mart',
    category: 'retail',
    description: 'Convenience store with essentials',
    logo_url: 'https://via.placeholder.com/100x100.png?text=Mart',
    latitude: 25.2284,
    longitude: 51.4732,
    address: 'Barwa Village',
    rating: 4.2,
    stamps_required: 15,
    reward_description: '50 QAR Shopping Voucher',
    nfc_tag_id: 'SHOP_BVM017',
    qr_code: 'QR_BVM017',
  },
  {
    name: 'Old Airport Wellness Spa',
    category: 'spa',
    description: 'Relaxation and therapy center',
    logo_url: 'https://via.placeholder.com/100x100.png?text=Wellness',
    latitude: 25.2614,
    longitude: 51.5609,
    address: 'Old Airport Road',
    rating: 4.7,
    stamps_required: 8,
    reward_description: 'Free Facial Treatment',
    nfc_tag_id: 'SHOP_OAW018',
    qr_code: 'QR_OAW018',
  },
  {
    name: 'Dafna Salon & Spa',
    category: 'salon',
    description: 'Full-service beauty salon',
    logo_url: 'https://via.placeholder.com/100x100.png?text=Beauty',
    latitude: 25.3105,
    longitude: 51.5217,
    address: 'Al Dafna, West Bay',
    rating: 4.6,
    stamps_required: 10,
    reward_description: 'Free Manicure',
    nfc_tag_id: 'SHOP_DSS019',
    qr_code: 'QR_DSS019',
  },
  {
    name: 'Musheireb Coffee Roasters',
    category: 'coffee',
    description: 'Artisanal coffee roasting and tasting',
    logo_url: 'https://via.placeholder.com/100x100.png?text=Roaster',
    latitude: 25.2856,
    longitude: 51.5294,
    address: 'Msheireb',
    rating: 4.9,
    stamps_required: 10,
    reward_description: 'Free Bag of Coffee Beans',
    nfc_tag_id: 'SHOP_MCR020',
    qr_code: 'QR_MCR020',
  },
];

export const DOHA_CENTER = {
  latitude: 25.2854,
  longitude: 51.5310,
};
